<?php /** @var \Magento\Store\Block\Switcher $block */ ?>
<?= df_flag_link() ?>
<?php if (count($block->getGroups())>1): ?>
<div class="switcher store switcher-store" id="switcher-store">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Select Store') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <?php foreach ($block->getGroups() as $g): ?>
        <?php if ($g->getId() == $block->getCurrentGroupId()): ?>
            <div class="action toggle switcher-trigger"
                 role="button"
                 tabindex="0"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true"
                 id="switcher-store-trigger"
			>
				<?= df_flag_span($g->getDefaultStore()->getCode()) ?>
                <strong><span><?= $block->escapeHtml($g->getName()) ?></span></strong>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($block->getGroups() as $g): ?>
            <?php if (!($g->getId() == $block->getCurrentGroupId())): ?>
                <li class="switcher-option">
                    <a href="#"
                       data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($g->getDefaultStore()); ?>'>
                        <?php echo $block->escapeHtml($g->getName()) ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>